apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-dependency-failure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-dep-failure
  template:
    metadata:
      labels:
        app: fastapi-dep-failure
    spec:
      containers:
      - name: fastapi
        image: fastapi-crash-dep-failure:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        # Como no existe ningún servicio llamado 'db-service' en el cluster, 
        # el script fallará al intentar hacer el socket.create_connection.
      
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
