apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-missing-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-config
  template:
    metadata:
      labels:
        app: fastapi-config
    spec:
      containers:
      - name: fastapi
        image: fastapi-crash-test:latest
        ports:
        - containerPort: 8000
        # No se define el volumen con el archivo de configuración, por lo que fallará
      
        resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
